<?php require_once __DIR__ . '/app/auth.php'; require_login(); csrf_check(); $pdo=db();
if($_SERVER['REQUEST_METHOD']==='POST'){
  $action=$_POST['action']??''; $id=(int)($_POST['id']??0);
  if($action==='save'){
    $code=trim($_POST['customer_code'] ?: next_customer_code($pdo));
    $data=[$code,trim($_POST['name']),trim($_POST['address']),trim($_POST['phone']),(int)$_POST['package_id'],trim($_POST['registered_at']),(int)$_POST['due_day'],isset($_POST['is_active'])?1:0,trim($_POST['router_name']??''),trim($_POST['onu_name']??''),trim($_POST['notes'])];
    if($id){$data[]=$id;$pdo->prepare('UPDATE customers SET customer_code=?,name=?,address=?,phone=?,package_id=?,registered_at=?,due_day=?,is_active=?,router_name=?,onu_name=?,notes=? WHERE id=?')->execute($data);}
    else {$pdo->prepare('INSERT INTO customers(customer_code,name,address,phone,package_id,registered_at,due_day,is_active,router_name,onu_name,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?)')->execute($data);} }
  if($action==='toggle' && $id){$pdo->prepare('UPDATE customers SET is_active=1-is_active WHERE id=?')->execute([$id]);}
  redirect('customers.php');
}
require_once __DIR__ . '/app/layout.php'; $month=current_month(); $filter=$_GET['filter']??'all'; $mode=$_GET['action']??'';
$packages=$pdo->query('SELECT * FROM packages WHERE is_active=1 ORDER BY price ASC')->fetchAll();
$edit=null; if($mode==='new'){$mode='form';} if(isset($_GET['edit'])){$st=$pdo->prepare('SELECT * FROM customers WHERE id=?');$st->execute([(int)$_GET['edit']]);$edit=$st->fetch(); $mode='form';}
$q=trim($_GET['q']??''); $where=[]; $args=[$month]; if($q!==''){$where[]='(c.name LIKE ? OR c.customer_code LIKE ? OR c.phone LIKE ? OR c.address LIKE ? OR c.router_name LIKE ? OR c.onu_name LIKE ? OR c.notes LIKE ?)';$args=array_merge($args,array_fill(0,7,"%$q%"));}
if($filter==='paid') {$where[]='(SELECT COUNT(*) FROM payments pay WHERE pay.customer_id=c.id AND pay.invoice_month=?) > 0'; $args[]=$month;}
if($filter==='unpaid') {$where[]='(SELECT COUNT(*) FROM payments pay WHERE pay.customer_id=c.id AND pay.invoice_month=?) = 0'; $args[]=$month;}
if($filter==='on') {$where[]='c.is_active=1';} if($filter==='off') {$where[]='c.is_active=0';}
$whereSql=$where?'WHERE '.implode(' AND ',$where):'';
$st=$pdo->prepare("SELECT c.*,p.name package_name,p.price,(SELECT COUNT(*) FROM payments pay WHERE pay.customer_id=c.id AND pay.invoice_month=?) is_paid FROM customers c LEFT JOIN packages p ON p.id=c.package_id $whereSql ORDER BY c.name ASC"); $st->execute($args); $rows=$st->fetchAll();
$total=count($rows); $paid=0; foreach($rows as $tmpRow){ if((int)$tmpRow['is_paid']>0) $paid++; } $unpaid=$total-$paid;
render_header($mode==='form'?($edit?'Edit Pelanggan':'Tambah Pelanggan'):'Data Pelanggan'); ?>
<?php if($mode==='form'): ?>
<section class="customer-form-hero"><div><p class="eyebrow">Customer operations</p><h1><?=$edit?'Edit data pelanggan':'Tambah pelanggan baru'?></h1><p>Isi data pelanggan, langganan, dan identitas jaringan dalam form yang lebih rapi. Cocok untuk operator billing dan teknisi.</p></div><div class="hero-actions"><a class="btn soft" href="customers.php">← Kembali ke daftar</a><?php if($edit):?><a class="btn primary" href="payments.php?customer_id=<?=$edit['id']?>">Input Pembayaran</a><?php endif;?></div></section>
<form class="customer-workspace-form" method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?=e($edit['id']??0)?>">
  <div class="form-section-card"><div class="section-heading"><span>01</span><div><h2>Profil Pelanggan</h2><p>Identitas dasar untuk pencarian, invoice, dan komunikasi.</p></div></div><div class="form-grid"><div class="field"><label>ID Pelanggan</label><input name="customer_code" value="<?=e($edit['customer_code']??next_customer_code($pdo))?>"></div><div class="field"><label>Nama Pelanggan</label><input name="name" required value="<?=e($edit['name']??'')?>" placeholder="Nama lengkap pelanggan"></div><div class="field"><label>Telepon / WhatsApp</label><input name="phone" value="<?=e($edit['phone']??'')?>" placeholder="628xxxxxxxxxx"></div><div class="field"><label>Tanggal Registrasi</label><input name="registered_at" type="date" required value="<?=e($edit['registered_at']??date('Y-m-d'))?>"></div><div class="field wide"><label>Alamat</label><textarea name="address" rows="3" placeholder="Alamat lengkap / patokan lokasi"><?=e($edit['address']??'')?></textarea></div></div></div>
  <div class="form-section-card"><div class="section-heading"><span>02</span><div><h2>Langganan & Billing</h2><p>Paket, harga, jatuh tempo, dan status langganan.</p></div></div><div class="form-grid"><div class="field"><label>Paket Internet</label><select name="package_id" required><?php foreach($packages as $p):?><option value="<?=$p['id']?>" <?=($edit && $edit['package_id']==$p['id'])?'selected':''?>><?=e($p['name'])?> · <?=e($p['speed'])?> · <?=rupiah($p['price'])?></option><?php endforeach;?></select></div><div class="field"><label>Tanggal Jatuh Tempo</label><input name="due_day" type="number" min="1" max="31" value="<?=e($edit['due_day']??20)?>"></div><div class="field status-field"><label>Status Langganan</label><label class="switch-row"><input type="checkbox" name="is_active" <?=(!$edit||$edit['is_active'])?'checked':''?>> <span>Pelanggan ON / aktif</span></label></div></div></div>
  <div class="form-section-card"><div class="section-heading"><span>03</span><div><h2>Network / PPPoE</h2><p>Data teknis supaya billing tetap nyambung dengan operasional jaringan.</p></div></div><div class="form-grid"><div class="field"><label>Nama Router</label><input name="router_name" value="<?=e($edit['router_name']??'')?>" placeholder="Contoh: MIKROTIK AREA KREKEL"></div><div class="field"><label>Nama ONU</label><input name="onu_name" value="<?=e($edit['onu_name']??'')?>" placeholder="Contoh: 1/1/8:47_NAMA"></div><div class="field wide"><label>Catatan / Keterangan</label><textarea name="notes" rows="3" placeholder="Keterangan paket, username PPPoE, secret, lokasi, atau catatan teknis"><?=e($edit['notes']??'')?></textarea></div></div></div>
  <div class="sticky-form-actions"><div><b><?=$edit?'Simpan perubahan pelanggan':'Simpan pelanggan baru'?></b><p>Pastikan data paket dan jatuh tempo sudah benar sebelum disimpan.</p></div><div class="flex gap-2 flex-wrap"><a class="btn soft" href="customers.php">Batal</a><button class="btn primary" type="submit">Simpan Pelanggan</button></div></div>
</form>
<?php else: ?>
<div class="summary-row"><div class="summary-pill"><span class="text-slate-500 font-bold">Data tampil</span><b><?=$total?></b></div><div class="summary-pill"><span class="text-slate-500 font-bold">Lunas bulan ini</span><b><?=$paid?></b></div><div class="summary-pill"><span class="text-slate-500 font-bold">Belum lunas</span><b><?=$unpaid?></b></div></div>
<div class="card customer-list-card"><div class="panel-title"><div><p class="eyebrow">Customer database</p><h2>Database Pelanggan</h2><div class="filter-tabs mt-3"><?php foreach(['all'=>'Semua','paid'=>'Lunas','unpaid'=>'Belum Lunas','on'=>'ON','off'=>'OFF'] as $k=>$v):?><a class="<?=$filter===$k?'active':''?>" href="customers.php?filter=<?=$k?>"><?=$v?></a><?php endforeach;?></div></div><div class="customer-toolbar"><form class="flex gap-2 flex-wrap"><input type="hidden" name="filter" value="<?=e($filter)?>"><input class="rounded-xl border px-3 py-2" name="q" value="<?=e($q)?>" placeholder="Cari nama, ID, HP, router, ONU"><button class="btn soft xs">Cari</button></form><a class="btn primary" href="customers.php?action=new">+ Tambah Pelanggan</a></div></div><div class="table-wrap"><table class="responsive"><thead><tr><th>ID</th><th>Nama</th><th>Paket</th><th>Tagihan</th><th>Status</th><th>Aksi</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td data-label="ID"><b><?=e($r['customer_code'])?></b><div class="desktop-muted"><?=e($r['phone'])?></div></td><td data-label="Nama"><b><?=e($r['name'])?></b><br><small class="text-slate-500"><?=e($r['address'])?></small><?php if(!empty($r['router_name'])||!empty($r['onu_name'])):?><br><small class="text-slate-500">Router: <?=e($r['router_name']?:'-')?> · ONU: <?=e($r['onu_name']?:'-')?></small><?php endif;?></td><td data-label="Paket"><?=e($r['package_name']??'-')?><br><b><?=rupiah($r['price']??0)?></b></td><td data-label="Tagihan"><span class="pill <?=$r['is_paid']?'green':'orange'?>"><?=$r['is_paid']?'Lunas':'Belum'?></span><br><small class="text-slate-500">Tempo tgl <?=e($r['due_day'])?></small></td><td data-label="Status"><span class="pill <?=$r['is_active']?'green':'red'?>"><?=$r['is_active']?'ON':'OFF'?></span></td><td data-label="Aksi"><div class="table-actions"><a class="btn soft xs" href="customers.php?edit=<?=$r['id']?>">Edit</a><a class="btn primary xs" href="payments.php?customer_id=<?=$r['id']?>">Bayar</a><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="toggle"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="btn red xs" type="submit"><?=$r['is_active']?'OFF':'ON'?></button></form></div></td></tr><?php endforeach;if(!$rows):?><tr><td colspan="6">Belum ada pelanggan.</td></tr><?php endif;?></tbody></table></div></div>
<?php endif; ?>
<?php render_footer(); ?>
