<?php require_once __DIR__ . '/app/auth.php'; require_login(); csrf_check(); $pdo=db();
if($_SERVER['REQUEST_METHOD']==='POST'){
  $action=$_POST['action']??''; $id=(int)($_POST['id']??0);
  if($action==='save'){
    $code='EXP-'.date('Ymd-His').'-'.random_int(100,999);
    $data=[trim($_POST['title']), (int)preg_replace('/[^0-9]/','',$_POST['amount']??'0'), trim($_POST['spent_at']?:date('Y-m-d')), trim($_POST['method']??'Cash'), trim($_POST['notes']??'')];
    if($id){$data[]=$id; $pdo->prepare('UPDATE expenses SET title=?,amount=?,spent_at=?,method=?,notes=? WHERE id=?')->execute($data);}
    else {$pdo->prepare('INSERT INTO expenses(expense_code,title,amount,spent_at,method,notes) VALUES(?,?,?,?,?,?)')->execute(array_merge([$code],$data));}
  }
  if($action==='delete' && $id){$pdo->prepare('DELETE FROM expenses WHERE id=?')->execute([$id]);}
  redirect('expenses.php');
}
require_once __DIR__ . '/app/layout.php'; $month=$_GET['month']??current_month();
$edit=null; if(isset($_GET['edit'])){$st=$pdo->prepare('SELECT * FROM expenses WHERE id=?');$st->execute([(int)$_GET['edit']]);$edit=$st->fetch();}
$st=$pdo->prepare("SELECT * FROM expenses WHERE substr(spent_at,1,7)=? ORDER BY spent_at DESC,id DESC"); $st->execute([$month]); $rows=$st->fetchAll();
$total=0; foreach($rows as $r){$total+=(int)$r['amount'];}
render_header('Pengeluaran'); ?>
<div class="hero-strip report-hero"><div class="hero-card"><p class="font-black uppercase tracking-[.18em] text-white/75 text-xs mb-2">Expense control</p><h2>Catat pengeluaran operasional supaya balance bulan ini lebih akurat.</h2><p class="text-white/85">Modul ini dasar dulu: input, edit, hapus, dan rekap pengeluaran bulanan.</p></div><div class="quick-card"><p class="eyebrow">Total bulan ini</p><h2 class="text-2xl font-black tracking-tight mb-3"><?=rupiah($total)?></h2><div class="text-slate-500 font-bold"><?=count($rows)?> transaksi</div></div></div>
<div class="grid-2"><form class="card form-card" method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?=e($edit['id']??0)?>"><div class="panel-title"><h2><?=$edit?'Edit':'Tambah'?> Pengeluaran</h2></div><div class="form-grid"><div class="field"><label>Judul</label><input name="title" required value="<?=e($edit['title']??'')?>" placeholder="Contoh: biaya teknisi"></div><div class="field"><label>Nominal</label><input name="amount" required value="<?=e($edit['amount']??'')?>" placeholder="150000"></div><div class="field"><label>Tanggal</label><input type="date" name="spent_at" required value="<?=e($edit['spent_at']??date('Y-m-d'))?>"></div><div class="field"><label>Metode</label><select name="method"><option <?=($edit['method']??'')==='Cash'?'selected':''?>>Cash</option><option <?=($edit['method']??'')==='Transfer'?'selected':''?>>Transfer</option><option <?=($edit['method']??'')==='Lainnya'?'selected':''?>>Lainnya</option></select></div><div class="field" style="grid-column:1/-1"><label>Catatan</label><textarea name="notes" rows="2"><?=e($edit['notes']??'')?></textarea></div></div><button class="btn primary mt-5">Simpan Pengeluaran</button></form><div class="card"><div class="panel-title"><div><h2>Pengeluaran Bulan Ini</h2><p class="text-slate-500 font-bold text-sm"><?=e($month)?></p></div><form class="flex gap-2"><input class="rounded-xl border px-3 py-2" type="month" name="month" value="<?=e($month)?>"><button class="btn soft xs">Filter</button></form></div><div class="table-wrap"><table class="responsive"><thead><tr><th>Tanggal</th><th>Judul</th><th>Nominal</th><th>Metode</th><th>Aksi</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td data-label="Tanggal"><?=e($r['spent_at'])?></td><td data-label="Judul"><b><?=e($r['title'])?></b><br><small class="text-slate-500"><?=e($r['notes'])?></small></td><td data-label="Nominal"><b><?=rupiah($r['amount'])?></b></td><td data-label="Metode"><?=e($r['method'])?></td><td data-label="Aksi"><div class="table-actions"><a class="btn soft xs" href="expenses.php?edit=<?=$r['id']?>">Edit</a><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="btn red xs" onclick="return confirm('Hapus pengeluaran ini?')">Hapus</button></form></div></td></tr><?php endforeach;if(!$rows):?><tr><td colspan="5">Belum ada pengeluaran bulan ini.</td></tr><?php endif;?></tbody></table></div></div></div>
<?php render_footer(); ?>
