<?php
require_once __DIR__ . '/app/auth.php';
require_login();
require_once __DIR__ . '/app/layout.php';
$pdo=db();
$s=app_stats($pdo);
$month=current_month();
$due=$pdo->query("SELECT c.*,p.name package_name,p.price FROM customers c LEFT JOIN packages p ON p.id=c.package_id ORDER BY c.due_day ASC,c.name ASC LIMIT 8")->fetchAll();
$last=$pdo->query("SELECT pay.*,c.name customer_name FROM payments pay JOIN customers c ON c.id=pay.customer_id ORDER BY pay.paid_at DESC,pay.id DESC LIMIT 8")->fetchAll();
$customerSql="SELECT c.*,p.name package_name,p.price,(SELECT COUNT(*) FROM payments pay WHERE pay.customer_id=c.id AND pay.invoice_month=?) is_paid FROM customers c LEFT JOIN packages p ON p.id=c.package_id ORDER BY c.name ASC LIMIT 12";
$stmt=$pdo->prepare($customerSql); $stmt->execute([$month]); $dashCustomers=$stmt->fetchAll();
$stmt=$pdo->prepare("SELECT c.*,p.name package_name,p.price,(SELECT COUNT(*) FROM payments pay WHERE pay.customer_id=c.id AND pay.invoice_month=?) is_paid FROM customers c LEFT JOIN packages p ON p.id=c.package_id WHERE (SELECT COUNT(*) FROM payments pay WHERE pay.customer_id=c.id AND pay.invoice_month=?) > 0 ORDER BY c.name ASC LIMIT 12"); $stmt->execute([$month,$month]); $dashPaid=$stmt->fetchAll();
$stmt=$pdo->prepare("SELECT c.*,p.name package_name,p.price,(SELECT COUNT(*) FROM payments pay WHERE pay.customer_id=c.id AND pay.invoice_month=?) is_paid FROM customers c LEFT JOIN packages p ON p.id=c.package_id WHERE (SELECT COUNT(*) FROM payments pay WHERE pay.customer_id=c.id AND pay.invoice_month=?) = 0 ORDER BY c.due_day ASC,c.name ASC LIMIT 12"); $stmt->execute([$month,$month]); $dashUnpaid=$stmt->fetchAll();
function dashboard_customer_rows(array $rows, string $empty): void { foreach($rows as $c): ?>
<tr><td data-label="ID"><b><?=e($c['customer_code'])?></b><br><small class="text-slate-500"><?=e($c['phone'] ?? '')?></small></td><td data-label="Nama"><b><?=e($c['name'])?></b><br><small class="text-slate-500"><?=e($c['address'] ?? '')?></small></td><td data-label="Paket"><?=e($c['package_name'] ?? '-')?><br><b><?=rupiah($c['price'] ?? 0)?></b></td><td data-label="Tempo">Tgl <?=e($c['due_day'])?></td><td data-label="Status"><span class="pill <?=$c['is_active']?'green':'red'?>"><?=$c['is_active']?'ON':'OFF'?></span> <span class="pill <?=$c['is_paid']?'green':'orange'?>"><?=$c['is_paid']?'Lunas':'Belum'?></span></td><td data-label="Aksi"><div class="table-actions"><a class="btn soft xs" href="customers.php?edit=<?=$c['id']?>">Edit</a><a class="btn primary xs" href="payments.php?customer_id=<?=$c['id']?>">Bayar</a></div></td></tr>
<?php endforeach; if(!$rows): ?><tr><td colspan="6"><?=e($empty)?></td></tr><?php endif; }
render_header('Dashboard Billing'); ?>
<section class="hero-strip"><div class="hero-card"><p class="font-black uppercase tracking-[.18em] text-white/75 text-xs mb-2">Dentanet Billing Workspace</p><h2>Workspace billing internet yang ringkas, elegan, dan siap dipakai operator setiap hari.</h2><p class="text-white/85">Pantau pemasukan, tagihan belum lunas, dan pelanggan aktif dalam alur kerja yang lebih tenang.</p></div><div class="quick-card"><p class="eyebrow">Quick actions</p><h2 class="text-2xl font-black tracking-tight mb-3">Mulai kerja</h2><div class="flex flex-wrap gap-2"><a class="btn primary" href="customers.php?action=new">+ Pelanggan</a><a class="btn soft" href="payments.php?action=new">+ Pembayaran</a></div></div></section>
<section class="cards status-grid command-cards">
  <a class="card metric status-card status-blue" href="customers.php"><div class="status-icon">👥</div><small>Data Pelanggan</small><strong><?=$s['total']?></strong><span class="pill blue">Semua pelanggan</span><span class="more-link">Buka data →</span></a>
  <a class="card metric status-card status-green" href="customers.php?filter=paid"><div class="status-icon">✓</div><small>Pelanggan Sudah Lunas</small><strong><?=$s['paid']?></strong><span class="pill green"><?=e($s['month'])?></span><span class="more-link">Lihat lunas →</span></a>
  <a class="card metric status-card status-amber" href="customers.php?filter=unpaid"><div class="status-icon">!</div><small>Pelanggan Belum Lunas</small><strong><?=$s['unpaid']?></strong><span class="pill orange">Perlu follow up</span><span class="more-link">Lihat tagihan →</span></a>
  <a class="card metric status-card status-teal" href="reports.php?month=<?=e($s['month'])?>"><div class="status-icon">Rp</div><small>Pemasukan Bulan Ini</small><strong><?=rupiah($s['monthIncome'])?></strong><span class="pill blue"><?=e($s['month'])?></span><span class="more-link">Buka laporan →</span></a>
  <a class="card metric status-card status-cyan" href="reports.php"><div class="status-icon">↗</div><small>Pemasukan Hari Ini</small><strong><?=rupiah($s['todayIncome'])?></strong><span class="pill green">Hari ini</span><span class="more-link">Detail transaksi →</span></a>
  <a class="card metric status-card status-red" href="expenses.php"><div class="status-icon">↘</div><small>Pengeluaran Bulan Ini</small><strong><?=rupiah($s['monthExpense'])?></strong><span class="pill red">Operasional</span><span class="more-link">Kelola nanti →</span></a>
  <a class="card metric status-card status-violet" href="reports.php?month=<?=e($s['month'])?>"><div class="status-icon">Σ</div><small>Balance Bulan Ini</small><strong><?=rupiah($s['monthBalance'])?></strong><span class="pill <?=$s['monthBalance']>=0?'green':'red'?>">Income - expense</span><span class="more-link">Analisa →</span></a>
</section>

<section class="dashboard-tabs card">
  <div class="tab-head">
    <div><p class="eyebrow">Customer workspace</p><h2>Data pelanggan bulan ini</h2></div>
    <div class="tab-buttons"><button class="active" data-tab="all">Data Pelanggan</button><button data-tab="paid">Sudah Lunas</button><button data-tab="unpaid">Belum Lunas</button></div>
  </div>
  <div class="tab-panel active" id="tab-all"><div class="panel-title"><h3>Data Pelanggan</h3><a class="btn soft xs" href="customers.php">Buka halaman pelanggan</a></div><div class="table-wrap"><table class="responsive"><thead><tr><th>ID</th><th>Nama</th><th>Paket</th><th>Tempo</th><th>Status</th><th>Aksi</th></tr></thead><tbody><?php dashboard_customer_rows($dashCustomers,'Belum ada pelanggan.'); ?></tbody></table></div></div>
  <div class="tab-panel" id="tab-paid"><div class="panel-title"><h3>Pelanggan Sudah Lunas</h3><a class="btn soft xs" href="customers.php?filter=paid">Lihat semua lunas</a></div><div class="table-wrap"><table class="responsive"><thead><tr><th>ID</th><th>Nama</th><th>Paket</th><th>Tempo</th><th>Status</th><th>Aksi</th></tr></thead><tbody><?php dashboard_customer_rows($dashPaid,'Belum ada pelanggan lunas bulan ini.'); ?></tbody></table></div></div>
  <div class="tab-panel" id="tab-unpaid"><div class="panel-title"><h3>Pelanggan Belum Lunas</h3><a class="btn soft xs" href="customers.php?filter=unpaid">Lihat semua belum lunas</a></div><div class="table-wrap"><table class="responsive"><thead><tr><th>ID</th><th>Nama</th><th>Paket</th><th>Tempo</th><th>Status</th><th>Aksi</th></tr></thead><tbody><?php dashboard_customer_rows($dashUnpaid,'Tidak ada tunggakan bulan ini.'); ?></tbody></table></div></div>
</section>
<script>
document.querySelectorAll('.tab-buttons button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.tab-buttons button').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.tab-panel').forEach(p=>p.classList.remove('active'));btn.classList.add('active');document.getElementById('tab-'+btn.dataset.tab).classList.add('active');}));
</script>

<section class="grid-2"><div class="card"><div class="panel-title"><h2>Pelanggan & Jatuh Tempo</h2><a class="btn soft" href="customers.php">Lihat semua</a></div><div class="table-wrap"><table class="responsive"><thead><tr><th>ID</th><th>Nama</th><th>Paket</th><th>Jatuh Tempo</th><th>Status</th></tr></thead><tbody><?php foreach($due as $c):?><tr><td data-label="ID"><b><?=e($c['customer_code'])?></b></td><td data-label="Nama"><?=e($c['name'])?></td><td data-label="Paket"><?=e($c['package_name'] ?? '-')?></td><td data-label="Tempo">Tgl <?=e($c['due_day'])?></td><td data-label="Status"><span class="pill <?=$c['is_active']?'green':'red'?>"><?=$c['is_active']?'ON':'OFF'?></span></td></tr><?php endforeach;if(!$due):?><tr><td colspan="5">Belum ada pelanggan.</td></tr><?php endif;?></tbody></table></div></div><div class="card"><div class="panel-title"><h2>Pembayaran Terakhir</h2><a class="btn soft" href="payments.php">Detail</a></div><div class="table-wrap"><table class="responsive"><thead><tr><th>Tanggal</th><th>Pelanggan</th><th>Nominal</th></tr></thead><tbody><?php foreach($last as $p):?><tr><td data-label="Tanggal"><?=e($p['paid_at'])?></td><td data-label="Pelanggan"><?=e($p['customer_name'])?></td><td data-label="Nominal"><b><?=rupiah($p['amount'])?></b></td></tr><?php endforeach;if(!$last):?><tr><td colspan="3">Belum ada pembayaran.</td></tr><?php endif;?></tbody></table></div></div></section>
<?php render_footer(); ?>
