<?php require_once __DIR__.'/app/db.php'; $pdo=db();
if($_SERVER['REQUEST_METHOD']==='POST'){
    $action=$_POST['action']??'';
    if($action==='save_customer'){
        $code=trim($_POST['customer_code']??'') ?: next_customer_code($pdo);
        $stmt=$pdo->prepare('INSERT INTO customers(customer_code,name,phone,address,package_name,monthly_fee,due_day,router_name,pppoe_user,status,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?)');
        $stmt->execute([$code,trim($_POST['name']??''),trim($_POST['phone']??''),trim($_POST['address']??''),trim($_POST['package_name']??''),money_to_int($_POST['monthly_fee']??0),(int)($_POST['due_day']??20),trim($_POST['router_name']??''),trim($_POST['pppoe_user']??''),trim($_POST['status']??'active'),trim($_POST['notes']??'')]);
        redirect('index.php?saved=1');
    }
}
$q=trim($_GET['q']??'');
$where=''; $args=[];
if($q!==''){ $where='WHERE name LIKE ? OR customer_code LIKE ? OR phone LIKE ? OR address LIKE ? OR router_name LIKE ? OR pppoe_user LIKE ?'; $args=array_fill(0,6,"%$q%"); }
$st=$pdo->prepare("SELECT * FROM customers $where ORDER BY id DESC"); $st->execute($args); $customers=$st->fetchAll();
$total=(int)$pdo->query('SELECT COUNT(*) FROM customers')->fetchColumn();
$active=(int)$pdo->query("SELECT COUNT(*) FROM customers WHERE status='active'")->fetchColumn();
$income=(int)$pdo->query('SELECT COALESCE(SUM(monthly_fee),0) FROM customers')->fetchColumn();
$nextCode=next_customer_code($pdo);
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Billing Internet v2</title><link rel="stylesheet" href="assets/style.css"></head>
<body><div class="shell"><aside class="sidebar"><div class="brand"><div class="logo">B2</div><div><b>Billing v2</b><span>Internet Workspace</span></div></div><nav><a class="active" href="#dashboard">Dashboard</a><a href="#customers">Pelanggan</a><a href="#add">Tambah Pelanggan</a></nav><div class="side-note"><b>Versi 2</b><p>Konsep baru. V1 tetap aman, v2 dibangun terpisah di folder /v2.</p></div></aside><main class="main"><section class="hero" id="dashboard"><div><p class="eyebrow">Modern ISP Billing</p><h1>Billing internet yang bersih, cepat, dan enak dipakai operator.</h1><p>Fokus tahap awal: database pelanggan dan form tambah pelanggan yang proper. Fitur billing lanjutan kita bangun bertahap.</p><div class="hero-actions"><a class="btn primary" href="#add">+ Tambah Pelanggan</a><a class="btn ghost" href="#customers">Lihat Data</a></div></div><div class="hero-card"><span>Estimasi tagihan aktif</span><strong><?=rupiah($income)?></strong><small>berdasarkan total biaya bulanan pelanggan</small></div></section><?php if(isset($_GET['saved'])):?><div class="alert">Pelanggan berhasil disimpan.</div><?php endif;?>
<section class="stats"><div class="stat blue"><span>Total Pelanggan</span><b><?=$total?></b><small>semua data</small></div><div class="stat green"><span>Pelanggan Aktif</span><b><?=$active?></b><small>status active</small></div><div class="stat amber"><span>Estimasi MRR</span><b><?=rupiah($income)?></b><small>biaya bulanan</small></div></section>
<section class="grid"><div class="card list-card" id="customers"><div class="card-head"><div><p class="eyebrow">Customer database</p><h2>Data Pelanggan</h2></div><form class="search"><input name="q" value="<?=e($q)?>" placeholder="Cari nama, ID, HP, router, PPPoE"><button class="btn ghost">Cari</button></form></div><div class="table-wrap"><table><thead><tr><th>ID</th><th>Pelanggan</th><th>Paket</th><th>Network</th><th>Status</th></tr></thead><tbody><?php foreach($customers as $c):?><tr><td><b><?=e($c['customer_code'])?></b><br><small><?=e($c['phone'])?></small></td><td><b><?=e($c['name'])?></b><br><small><?=e($c['address'])?></small></td><td><?=e($c['package_name']?:'-')?><br><b><?=rupiah($c['monthly_fee'])?></b><small> / bulan</small></td><td><small>Router: <?=e($c['router_name']?:'-')?></small><br><small>PPPoE: <?=e($c['pppoe_user']?:'-')?></small></td><td><span class="pill <?=e($c['status'])?>"><?=e(strtoupper($c['status']))?></span><br><small>Tempo tgl <?=e($c['due_day'])?></small></td></tr><?php endforeach;if(!$customers):?><tr><td colspan="5" class="empty">Belum ada pelanggan. Tambahkan pelanggan pertama dari form di samping.</td></tr><?php endif;?></tbody></table></div></div>
<form class="card form-card" id="add" method="post"><input type="hidden" name="action" value="save_customer"><div class="card-head"><div><p class="eyebrow">New customer</p><h2>Tambah Pelanggan</h2></div></div><div class="form-grid"><label>ID Pelanggan<input name="customer_code" value="<?=e($nextCode)?>"></label><label>Nama Pelanggan<input name="name" required placeholder="Nama lengkap"></label><label>No HP / WhatsApp<input name="phone" placeholder="628xxxxxxxxxx"></label><label>Paket Internet<input name="package_name" placeholder="Home 10 Mbps"></label><label>Biaya Bulanan<input name="monthly_fee" inputmode="numeric" placeholder="150000"></label><label>Tgl Jatuh Tempo<input type="number" min="1" max="31" name="due_day" value="20"></label><label>Nama Router<input name="router_name" placeholder="MikroTik Area A"></label><label>Username PPPoE<input name="pppoe_user" placeholder="nama@denta.net"></label><label>Status<select name="status"><option value="active">Active</option><option value="inactive">Inactive</option><option value="isolated">Isolated</option></select></label><label class="wide">Alamat<textarea name="address" rows="3" placeholder="Alamat pelanggan"></textarea></label><label class="wide">Catatan<textarea name="notes" rows="3" placeholder="Catatan teknis / billing"></textarea></label></div><button class="btn primary full">Simpan Pelanggan</button></form></section></main></div></body></html>
